### ISSUE TITLE
cannot import name 'cached_property'

### ISSUE THREAD

**Issue by ibtehajali67** [sundios/Google-rank-tracker#9]
Traceback (most recent call last):
  File "rank.py", line 5, in <module>
    from robobrowser import RoboBrowser
  File "/home/ibtehaj/Documents/keyword/env/lib/python3.6/site-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/home/ibtehaj/Documents/keyword/env/lib/python3.6/site-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property'

**Comment by ibtehajali67** [comment]
its work for me
Downgrade Werkzeug to 0.16.1

pip3 install --upgrade Werkzeug==0.16.1
If you do a pip3 list you may see something like this:

Flask              1.1.2
Werkzeug           0.16.1
